version: '3.4'

networks:
  backend:
    driver: bridge

services:
  prn231_group5.assignment1.api:
    image: ${DOCKER_REGISTRY-}prn231group5assignment1
    build:
      context: .
      dockerfile: PRN231_Group5.Assignment1.API/Dockerfile
    environment:
      - 'ConnectionStrings__FStoreDB=User ID=sa;Password=Password.1;Server=app_db,1433;Database=FStoreDB;TrustServerCertificate=True;MultiSubnetFailover=True;Pooling=True;'
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - app_db
    ports:
      - '8088:80'
    networks:
      - backend
  app_db:
    image: 'mcr.microsoft.com/azure-sql-edge'
    container_name: 'app_db'
    environment:
      SA_PASSWORD: 'Password.1'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    restart: always
    networks:
      - backend
